### ISSUE TITLE
uploadcare.file.upload

### ISSUE THREAD

**Issue by iw2rmb** [RexMorgan/uploadcare-node#17]
`Error: Invalid JSON from uploadcare.com
    at IncomingMessage.<anonymous> (/Users/vk/GitHub/ecomp-be/node_modules/uploadcare/lib/main.js:39:31)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by iw2rmb** [comment]
Figured that UC returns `Uploading of these files types is not allowed on your current plan.` instead of JSON.
